### PR TITLE
[RFC] Content negotiation middleware + minor tweaks

### PR DESCRIPTION
**Pull request by willdurand**

### CODE REVIEW

**Comment by willdurand** [comment]
ah thx, but I flagged the PR as "RFC" as I don't have much XP with Slim..

**Comment by codeguy** [comment]
Ah didn't catch that. No one is using this repo yet so no harm done. What you have looks fine. I'll test it out tonight and let you know if anything needs tweaking.

**Comment by willdurand** [comment]
alright :)

**Comment by codeguy** [comment]
Pushed a tiny fix changing "ACCEPT" to "HTTP_ACCEPT". Works great.

**Comment by codeguy** [comment]
Just thinking out loud... we could add a way to define supported content types for a given route, and this could affect route matching against the current request. If the route supports any of the requested content types as parsed by your Negotiation library, the route will match and the response can be automatically set to the best content type.

Or do you think this is too much convention and should be delegated to the app developer?

**Comment by willdurand** [comment]
I choose `ACCEPT` over `HTTP_ACCEPT` as I saw the `Environment` class used that key... Didn't walk through the code..

I am not sure that routing based on the Accept header would make sense. The client always performs the same "action", it only decides the response format that it would like to get. A better alternative would be a "view" layer that takes data and serializes them depending on the best format parsed by Negotiation. It would make things easier for the app developer.

**Pull request merged**
